name: CI_CD
on:
  push:
    branches:
      - main
env:
  SECRET: ${{secrets.DEMO_SECRET}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Secret auswerten
        run: >
          echo "LÃ¤nge des Secrets: " 
          ${#SECRET}
      - name: Java aufsetzen
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
