name: CI_CD
on:
  push:
    branches:
      - main
env:
  SECRET: ${{secrets.DEMO_SECRET}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Secret auswerten
        run: >
          echo "LÃ¤nge des Secrets: " 
          ${#SECRET}
